package meta

import (
	"context"
	"errors"
	"fmt"
	"net/url"
)

type Paging struct {
	Cursors struct {
		Before string `json:"before,omitempty"`
		After  string `json:"after,omitempty"`
	} `json:"cursors,omitempty"`
	Next     string `json:"next,omitempty"`
	Previous string `json:"previous,omitempty"`
}

type GraphPage[T any] struct {
	Data    []T    `json:"data"`
	Paging  Paging `json:"paging,omitempty"`
	Summary any    `json:"summary,omitempty"`
}

// CollectPages follows Meta's opaque paging URL until exhaustion. The token
// and appsecret_proof contained in a next URL are deliberately discarded and
// regenerated by Client.
func CollectPages[T any](
	ctx context.Context,
	client *Client,
	graphPath string,
	accessToken string,
	query url.Values,
) ([]T, error) {
	if client == nil {
		return nil, errors.New("meta: client is nil")
	}
	currentPath := graphPath
	currentQuery := cloneValues(query)
	var result []T

	// This guard catches a malformed/cyclic paging response while remaining
	// far above any realistic asset list.
	for pageNumber := 0; pageNumber < 10000; pageNumber++ {
		var page GraphPage[T]
		if err := client.Get(ctx, currentPath, accessToken, currentQuery, &page); err != nil {
			return nil, err
		}
		result = append(result, page.Data...)
		if page.Paging.Next == "" {
			return result, nil
		}
		currentPath = page.Paging.Next
		currentQuery = nil
	}
	return nil, fmt.Errorf("meta: paging exceeded safety limit")
}

func cloneValues(source url.Values) url.Values {
	if source == nil {
		return nil
	}
	clone := make(url.Values, len(source))
	for key, entries := range source {
		clone[key] = append([]string(nil), entries...)
	}
	return clone
}
