// Command fieldaudit compares this service's typed Meta specifications
// against the live Graph API.
//
// It is a development tool and is deliberately not built into the runtime
// image: it needs a real token and one live object of each type, and its
// output is a document to commit, not a service to run.
//
// Usage:
//
//	go run ./cmd/fieldaudit \
//	  -token "$USER_ACCESS_TOKEN" \
//	  -account 1234567890 \
//	  -campaign 23847... -adset 23848... -ad 23849... -creative 23850...
//
// With -account alone it probes only the Insights edge, which is the part
// that actually gates ingestion.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/watchers-factory/raze-ads/internal/meta"
	"github.com/watchers-factory/raze-ads/internal/meta/fieldaudit"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "fieldaudit:", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		token      = flag.String("token", os.Getenv("META_ACCESS_TOKEN"), "user access token")
		appID      = flag.String("app-id", os.Getenv("META_APP_ID"), "Meta app ID")
		appSecret  = flag.String("app-secret", os.Getenv("META_APP_SECRET"), "Meta app secret")
		apiVersion = flag.String("api-version", meta.DefaultAPIVersion, "Graph API version")
		accountID  = flag.String("account", "", "ad account ID, without the act_ prefix")
		campaignID = flag.String("campaign", "", "a live campaign ID")
		adSetID    = flag.String("adset", "", "a live ad set ID")
		adID       = flag.String("ad", "", "a live ad ID")
		creativeID = flag.String("creative", "", "a live ad creative ID")
		asJSON     = flag.Bool("json", false, "emit JSON instead of markdown")
		timeout    = flag.Duration("timeout", 2*time.Minute, "overall timeout")
	)
	flag.Parse()

	if strings.TrimSpace(*token) == "" {
		return errors.New("-token is required (or set META_ACCESS_TOKEN)")
	}
	if strings.TrimSpace(*appID) == "" || strings.TrimSpace(*appSecret) == "" {
		// Without these the client cannot compute appsecret_proof, which the
		// Graph API requires for server-side calls.
		return errors.New("-app-id and -app-secret are required (or set META_APP_ID / META_APP_SECRET)")
	}

	client, err := meta.NewClient(meta.ClientConfig{
		AppID:      *appID,
		AppSecret:  *appSecret,
		APIVersion: *apiVersion,
	})
	if err != nil {
		return err
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	var out strings.Builder
	fmt.Fprintf(&out, "# Meta field coverage (%s)\n\n", *apiVersion)
	fmt.Fprintf(&out, "Generated by `cmd/fieldaudit` against the live Graph API.\n\n")

	nodes := []struct {
		name string
		id   string
		spec any
	}{
		{"campaign", *campaignID, meta.CampaignSpec{}},
		{"adset", *adSetID, meta.AdSetSpec{}},
		{"ad", *adID, meta.AdSpec{}},
		{"adcreative", *creativeID, meta.CreativeSpec{}},
	}

	var reports []fieldaudit.FieldReport
	for _, node := range nodes {
		if strings.TrimSpace(node.id) == "" {
			fmt.Fprintf(os.Stderr, "skipping %s: no ID supplied\n", node.name)
			continue
		}
		metaFields, err := fieldaudit.NodeFields(ctx, client, *token, node.id)
		if err != nil {
			return fmt.Errorf("read %s metadata: %w", node.name, err)
		}
		report := fieldaudit.Compare(node.name, metaFields, fieldaudit.SpecFieldNames(node.spec))
		reports = append(reports, report)
		out.WriteString(report.Markdown())
	}

	var insights []fieldaudit.InsightFieldResult
	if strings.TrimSpace(*accountID) != "" {
		out.WriteString("## Insights fields accepted per level\n\n")
		out.WriteString("Determined by submitting the full candidate set and removing each " +
			"field Meta names in its `(#100)` rejection until the query succeeds. " +
			"Field validity varies by level, so each level is probed separately.\n\n")

		for _, level := range []meta.InsightLevel{
			meta.InsightLevelAccount,
			meta.InsightLevelCampaign,
			meta.InsightLevelAdSet,
			meta.InsightLevelAd,
		} {
			result, err := fieldaudit.ProbeInsightFields(
				ctx, client, *token, *accountID, level, meta.ExtendedInsightFields, 80,
			)
			if err != nil {
				return err
			}
			insights = append(insights, result)
			fmt.Fprintf(&out, "### %s\n\n", level)
			fmt.Fprintf(&out, "%d accepted, %d rejected.\n\n",
				len(result.Accepted), len(result.Rejected))
			if len(result.Rejected) > 0 {
				out.WriteString("Rejected at this level:\n\n")
				for _, name := range result.Rejected {
					fmt.Fprintf(&out, "- `%s`\n", name)
				}
				out.WriteString("\n")
			}
		}
	}

	if *asJSON {
		encoded, err := fieldaudit.EncodeJSON(map[string]any{
			"api_version": *apiVersion,
			"nodes":       reports,
			"insights":    insights,
		})
		if err != nil {
			return err
		}
		fmt.Println(encoded)
		return nil
	}
	fmt.Print(out.String())
	return nil
}
