package application

import (
	"github.com/watchers-factory/raze-ads/internal/meta"
	"github.com/watchers-factory/raze-ads/internal/rules"
)

func (s *Service) Capabilities() Capabilities {
	return Capabilities{
		MetaAPIVersion: s.Config.Meta.APIVersion,
		Objectives: []meta.Objective{
			meta.ObjectiveOutcomeAwareness,
			meta.ObjectiveOutcomeTraffic,
			meta.ObjectiveOutcomeEngagement,
			meta.ObjectiveOutcomeLeads,
			meta.ObjectiveOutcomeAppPromotion,
			meta.ObjectiveOutcomeSales,
		},
		Destinations: []meta.DestinationType{
			meta.DestinationWebsite,
			meta.DestinationApp,
			meta.DestinationAppLinksAutomatic,
			meta.DestinationFacebookPage,
			meta.DestinationOnPage,
			meta.DestinationOnPost,
		},
		OptimizationGoals: []meta.OptimizationGoal{
			meta.OptimizationGoalAutomatic,
			meta.OptimizationGoalAdRecallLift,
			meta.OptimizationGoalImpressions,
			meta.OptimizationGoalReach,
			meta.OptimizationGoalLinkClicks,
			meta.OptimizationGoalLandingPageViews,
			meta.OptimizationGoalThruPlay,
			meta.OptimizationGoalOffsiteConversions,
			meta.OptimizationGoalPageLikes,
			meta.OptimizationGoalPostEngagement,
			meta.OptimizationGoalProfileAndPageEngagement,
			meta.OptimizationGoalValue,
			meta.OptimizationGoalAppInstalls,
			meta.OptimizationGoalAppInstallsOffsiteConversions,
		},
		BillingEvents: []meta.BillingEvent{
			meta.BillingEventImpressions,
			meta.BillingEventLinkClicks,
			meta.BillingEventClicks,
			meta.BillingEventAppInstalls,
			meta.BillingEventThruPlay,
			meta.BillingEventPurchase,
		},
		BidStrategies: []meta.BidStrategy{
			meta.BidStrategyLowestCostWithoutCap,
			meta.BidStrategyLowestCostWithBidCap,
			meta.BidStrategyCostCap,
			meta.BidStrategyLowestCostMinROAS,
		},
		SpecialAdCategories: []meta.SpecialAdCategory{
			meta.SpecialAdCategoryNone,
			meta.SpecialAdCategoryOnlineGamblingGaming,
			meta.SpecialAdCategoryCredit,
			meta.SpecialAdCategoryEmployment,
			meta.SpecialAdCategoryFinancialProducts,
			meta.SpecialAdCategoryHousing,
			meta.SpecialAdCategoryIssuesElectionsPolitics,
		},
		CreativeFormats: []string{
			"single_image",
			"single_video",
			"carousel",
			"flexible_asset_feed",
			"existing_facebook_post",
			"existing_instagram_media",
		},
		RuleOperators: []rules.Operator{
			rules.OperatorGT,
			rules.OperatorGTE,
			rules.OperatorLT,
			rules.OperatorLTE,
			rules.OperatorEQ,
			rules.OperatorNEQ,
		},
		RuleActions:      []rules.Action{rules.ActionPause},
		RuleTargetLevels: []rules.TargetLevel{rules.TargetCampaign, rules.TargetAdSet, rules.TargetAd},
		CommonRuleMetrics: []string{
			"spend",
			"impressions",
			"clicks",
			"unique_clicks",
			"inline_link_clicks",
			"ctr",
			"cpc",
			"cpm",
			"actions.link_click",
			"actions.landing_page_view",
			"actions.view_content",
			"actions.add_to_cart",
			"actions.initiate_checkout",
			"actions.complete_registration",
			"actions.lead",
			"actions.purchase",
			"actions.subscribe",
			"actions.*",
			"actions.*.1d_click",
			"actions.*.1d_view",
			"actions.*.7d_click",
			"actions.*.7d_view",
			"action_values.*",
			"conversions.*",
			"conversion_values.*",
			"cost_per_action_type.*",
			"cost_per_conversion.*",
			"cpa.*",
			"conversion_cpa.*",
			"roas.*",
			"conversion_roas.*",
			"outbound_clicks.*",
			"outbound_clicks_ctr.*",
			"video_play_actions.*",
			"video_thruplay_watched_actions.*",
		},
		RawFieldsSupported: true,
		ExcludedCapabilities: []string{
			"instant_forms",
			"messaging_destinations",
			"catalog_sales",
		},
	}
}
